### ISSUE TITLE
Command line for unittest with pipenv

### ISSUE THREAD

**Issue by PhilippeGalvan** [garciparedes/jinete#91]
# Bug Report Details

## Description
```bash
pipenv python -m unittest discover tests
```
throws : 

```bash
Usage: pipenv [OPTIONS] COMMAND [ARGS]...
Try "pipenv -h" for help.

Error: No such command "python".
```

## Steps to Reproduce

```bash
cd jinete/
pipenv install --dev
pipenv python -m unittest discover tests
```

### Environment

Python 3.7
Fedora 30

## Expected behavior

Unittest should execute tests !

### Proposition : 
In Readme.md replace : 

```bash
pipenv python -m unittest discover tests
``` 
by
```bash
pipenv run python3 -m unittest discover tests
```

**Comment by garciparedes** [comment]
Hi @PhilippeGalvan!

Thank you for detecting this problem in the docs. The confusion comes because at early stages of the project I used `pipenv` but at some point I removed it I decided to simply use a `virtualenv` + `pip` setup.

Then, I think this reply also answers the #92 issue. I'll close the another issue and use this one to create a pull request with `README.md` clarifications.

**Comment by garciparedes** [comment]
I think the changes applied in the `README.md` file are enough to resolve this issue. 

Thanks again for submitting it @PhilippeGalvan! 🙂
